import { Project, SkillCategories } from "./types";

export const PROJECTS: Project[] = [
  {
    id: 1,
    title: "E-Commerce Platform",
    description: "A full-featured e-commerce platform with product listings, shopping cart, and secure checkout.",
    image: "https://images.pexels.com/photos/6214476/pexels-photo-6214476.jpeg",
    technologies: ["React", "Next.js", "Stripe", "Tailwind CSS"],
    category: "Web App",
    demoUrl: "https://example.com",
    githubUrl: "https://github.com",
  },
  {
    id: 2,
    title: "Finance Dashboard",
    description: "A comprehensive dashboard for tracking personal finances, investments, and budget planning.",
    image: "https://images.pexels.com/photos/7681096/pexels-photo-7681096.jpeg",
    technologies: ["React", "Chart.js", "Firebase", "Material UI"],
    category: "Web App",
    demoUrl: "https://example.com",
    githubUrl: "https://github.com",
  },
  {
    id: 3,
    title: "Task Management App",
    description: "A productivity app for managing tasks, projects, and team collaboration.",
    image: "https://images.pexels.com/photos/6177645/pexels-photo-6177645.jpeg",
    technologies: ["React", "Redux", "Node.js", "MongoDB"],
    category: "Web App",
    demoUrl: "https://example.com",
    githubUrl: "https://github.com",
  },
  {
    id: 4,
    title: "Fitness Tracker",
    description: "A mobile app for tracking workouts, nutrition, and fitness progress.",
    image: "https://images.pexels.com/photos/4482895/pexels-photo-4482895.jpeg",
    technologies: ["React Native", "Expo", "Firebase", "Redux"],
    category: "Mobile",
    demoUrl: "https://example.com",
    githubUrl: "https://github.com",
  },
  {
    id: 5,
    title: "Music Streaming App",
    description: "A music streaming platform with personalized recommendations and playlist management.",
    image: "https://images.pexels.com/photos/6770579/pexels-photo-6770579.jpeg",
    technologies: ["React Native", "Node.js", "MongoDB", "AWS"],
    category: "Mobile",
    demoUrl: "https://example.com",
    githubUrl: "https://github.com",
  },
  {
    id: 6,
    title: "Travel Website Redesign",
    description: "A complete redesign of a travel booking website focusing on user experience and conversion.",
    image: "https://images.pexels.com/photos/7412111/pexels-photo-7412111.jpeg",
    technologies: ["Figma", "Adobe XD", "Photoshop", "Illustrator"],
    category: "UI/UX",
    demoUrl: "https://example.com",
    githubUrl: "https://github.com",
  },
];

export const SKILLS: SkillCategories = {
  frontend: [
    { name: "HTML5", level: 95 },
    { name: "CSS3 / SASS", level: 90 },
    { name: "JavaScript", level: 92 },
    { name: "TypeScript", level: 85 },
    { name: "React", level: 90 },
    { name: "Next.js", level: 88 },
    { name: "Tailwind CSS", level: 92 },
    { name: "Vue.js", level: 80 },
  ],
  backend: [
    { name: "Node.js", level: 85 },
    { name: "Express", level: 82 },
    { name: "MongoDB", level: 78 },
    { name: "PostgreSQL", level: 75 },
    { name: "Firebase", level: 85 },
    { name: "RESTful APIs", level: 90 },
    { name: "GraphQL", level: 70 },
  ],
  tools: [
    { name: "Git & GitHub", level: 92 },
    { name: "Docker", level: 75 },
    { name: "Figma", level: 88 },
    { name: "Adobe XD", level: 80 },
    { name: "VS Code", level: 95 },
    { name: "Jest", level: 78 },
    { name: "Webpack", level: 75 },
  ],
};